services:
  _defaults:
    autoconfigure: true
  klimasofa.insert_tags:
    class: Klimasofa\InserttagsBundle\EventListener\InserttagsListener
    tags:
      - { name: contao.hook, hook: replaceInsertTags }
    public: true
